-- 1. 기존 테이블이 있다면 삭제 (초기화용)
DROP TABLE IF EXISTS SEARCH_TABLE;
DROP TABLE IF EXISTS SPAM_TABLE;
DROP TABLE IF EXISTS USER_TABLE;

-- 2. USER_TABLE 생성 (오타 수정 및 이메일 감싸기)
CREATE TABLE USER_TABLE (
    USER_ID CHAR(6) PRIMARY KEY,
    `E-mail` VARCHAR(30) UNIQUE,
    PSW VARCHAR(60) NOT NULL,
    IN_DATE DATETIME,
    AGE INT
);

-- 3. SPAM_TABLE 생성 (ST 글자수 크기 수정)
CREATE TABLE SPAM_TABLE (
    PHONE_NUM VARCHAR(15) PRIMARY KEY,
    SPAM_ST CHAR(3),
    RP_NUM INT, 
    COMMENT VARCHAR(50)
);

-- 4. SEARCH_TABLE 생성
CREATE TABLE SEARCH_TABLE (
    LOG_NUM INT PRIMARY KEY,
    PHONE_NUM VARCHAR(15),
    USER_ID CHAR(6),
    MISSING CHAR(1),
    SEARCH_DATE DATETIME,
    FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID)
);