CREATE TABLE USER_TALBE(
	USER_ID CHAR(6) PRIMARY KEY,
	E-mail VARCHAR(30) UNIQUE,
	PSW VARCHAR(60) NOT NULL,
	IN_DATE DATETIME,
	AGE INT
);


CREATE TABLE SPAM_TABLE(
	PHONE_NUM VARCHAR(15) PRIMARY KEY,
	SPAM_ST CHAR(3),
	RP_NUM INT, 
	COMMENT VARCHAR(50)
)

CREATE TABLE SEARCH_TABLE(
	LOG_NUM INT PRIMARY KEY,
	PHONE_NUM VARCHAR(15),
	USER_ID CHAR(6),
	MISSING CHAR(1),
	SEARCH_DATE DATETIME,
	FOREIGN KEY (USER_ID) REFERENCES USER_TABLE(USER_ID)
);

